routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Route::get('/mailable', function () {
    $payment = App\Payment::find(1);
    $invoice = $payment->invoice;
    return new App\Mail\SendInvoice($invoice);
});

Auth::routes();

Route::group(['middleware' => ['auth']], function(){
    Route::get('dashboard', 'DashboardController@index')->name('home');

    Route::get('bills', 'BillController@index');
    Route::post('bills/clear/{id}', 'BillController@clear');

    Route::get('downloads/invoice/{id}', 'TenantController@downloadInvoice');
    Route::get('downloads/receipt/{id}', 'TenantController@downloadReceipt');

    Route::get('properties', 'PropertyController@index');
    Route::post('properties/create', 'PropertyController@store');
    Route::post('properties/update/{id}', 'PropertyController@update');
    Route::post('properties/delete/{id}', 'PropertyController@delete');
    Route::get('properties/get_projection_data/{id}', 'PropertyController@getChart');
    Route::get('floors/get_projection_data/{id}', 'FloorController@getChart');
    Route::get('properties/{id}/floors', 'FloorController@index');
    Route::post('properties/floors/update/{id}', 'FloorController@update');
    Route::post('properties/floors/store/{property_id}', 'FloorController@store');
    Route::post('properties/floors/delete/{id}', 'FloorController@delete');
    Route::get('properties/get_floors/{id}', 'FloorController@getFloors');
    Route::get('properties/floor_units/{floor_id}', 'FloorUnitController@index');
    Route::post('properties/floor_units/store/{floor_id}', 'FloorUnitController@store');
    Route::post('properties/floor_units/update/{id}', 'FloorUnitController@update');
    Route::get('properties/floor_units/get/{floor_id}', 'FloorUnitController@getUnits');

    Route::get('properties/parking_spots/{floor_id}', 'ParkingSpotController@index');
    Route::post('properties/parking_spot/store/{floor_id}', 'ParkingSpotController@store');
    Route::post('properties/parking_spot/update/{id}', 'ParkingSpotController@update');
    Route::get('properties/parking_spots/get/{property_id}', 'ParkingSpotController@getSpots');

    Route::get('tenants', 'TenantController@index')->middleware('filter.params');
    Route::get('tenants/create', 'TenantController@create');
    Route::post('tenants/store', 'TenantController@store');
    Route::get('tenants/view/{id}', 'TenantController@edit');
    Route::post('tenants/update/{id}', 'TenantController@update');
    Route::get('tenants/invoice/{id}', 'InvoiceController@index');
    Route::post('tenants/delete/{id}', 'TenantController@delete');
    Route::get('tenants/document/{id}', 'TenantController@getDocument');
    Route::get('tenants/documents/{id}', 'TenantController@showDocuments');
    Route::get('tenants/fix/documents', 'TenantDocumentController@store');
    Route::post('tenants/documents/upload/{id}/{tag}', 'TenantDocumentController@upload');
    Route::get('tenants/documents/download/{id}/{tag}', 'TenantDocumentController@getDocument');
    Route::get('tenants/statements/{tenant}', 'TenantStatementController@index');
    Route::post('tenants/electricity_bill/create/{id}', 'ElectricityBillController@store');
    Route::get('tenants/electricity_bill/get/{id}', 'ElectricityBillController@getBillInfo');

    Route::get('payments', 'PaymentController@index')->middleware('filter.params');
    Route::get('payments/get', 'PaymentController@show');
    Route::get('payments/invoices/clear/create/{invoice_id}', 'PaymentController@create');
    Route::post('payments/invoices/clear/store/{invoice_id}', 'PaymentController@store');
    Route::get('payments/invoices/view/{invoice_id}', 'InvoiceController@show');
    Route::get('payments/invoices/download/{invoice_id}', 'InvoiceController@download');
    Route::get('payments/invoice', 'InvoiceController@index');
    Route::get('payments/document/{id}', 'PaymentController@getDocument');


    Route::get('settings', 'SettingController@index')->middleware('filter.params');

    Route::get('settings/bills/get', 'BillController@getSettings');
    Route::post('settings/bills/create', 'BillController@storeSetting');
    Route::post('settings/bills/update/{id}', 'BillController@updateSetting');
    Route::post('settings/bills/delete/{id}', 'BillController@deleteSetting');

    Route::post('settings/interest_rate/set', 'InterestRateController@store');
    Route::get('settings/interest_rate/get', 'InterestRateController@get');
    Route::post('settings/service_charge', 'ServiceChargeController@store');
    Route::get('settings/get_service_charge', 'ServiceChargeController@get');

    Route::post('settings/id_documents/add', 'IdDocumentController@store');
    Route::get('settings/id_documents/get', 'IdDocumentController@get');
    Route::post('settings/id_documents/delete', 'IdDocumentController@delete');

    Route::post('settings/payment_terms/add', 'PaymentTermController@store');
    Route::get('settings/payment_terms/get', 'PaymentTermController@get');
    Route::post('settings/payment_terms/delete', 'PaymentTermController@delete');
    Route::post('settings/payment_terms/update', 'PaymentTermController@update');

    Route::post('settings/reports/create', 'ReportControler@store');
    Route::get('settings/reports/get', 'ReportControler@get');
    Route::post('settings/reports/update/{id}', 'ReportControler@update');
    Route::post('settings/reports/delete/{id}', 'ReportControler@delete');

    Route::get('users', 'UserController@index');
    Route::post('user/create', 'UserController@store');
    Route::post('users/deactivate/{id}', 'UserController@deactivate');
    Route::post('users/activate/{id}', 'UserController@activate');
});

app/Invoice.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    protected $with = ['tenant'];

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    public function getDueOnAttribute($value)
    {
        return Carbon::parse($value);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public function receipts()
    {
        return $this->hasMany(Receipt::class);
    }

    public function statement()
    {
        return $this->hasMany(TenantStatement::class);
    }
}

app/Payment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Plank\Mediable\Mediable;

class Payment extends Model
{
    use SoftDeletes, Mediable;

    protected $with = ['media'];

    protected $guarded = [];

    protected $appends = ['document_url'];

    public function invoice()
    {
        return $this->belongsTo(Invoice::class);
    }

    public function receipt()
    {
        return $this->hasOne(Receipt::class);
    }

    public function getDocumentUrlAttribute()
    {
        $urls = [];
        $appDomain = url('/');
        foreach ($this->media as $photo) {

            $disk = $photo->disk;
            $directory = $photo->directory;
            $filename = $photo->filename;
            $extension = $photo->extension;



            $url = $disk.'/'.$directory.'/'.$filename.'.'.$extension;

            array_push($urls, $url);
        }

        return $urls[0];
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Events\PaymentAdded;
use App\Invoice;
use Barryvdh\DomPDF\Facade as PDF;
use App\Payment;
use App\PaymentMethod;
use App\Traits\HandlesInvoices;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Kamaln7\Toastr\Facades\Toastr;
use Maatwebsite\Excel\Facades\Excel;
use Plank\Mediable\MediaUploaderFacade as MediaUploader;

class PaymentController extends Controller
{
    use HandlesInvoices;

    public function index(Request $request)
    {
        $invoice = new Invoice();
        $query = $invoice->newQuery();

        if ($request->has('from') && $request->has('to')) {
            if (!empty($request->to) && !empty($request->from)) {
                $from = Carbon::parse($request->from)->format('Y-m-d H:i:s');;
                $to = Carbon::parse($request->to)->addSeconds(86399)->format('Y-m-d H:i:s');
                $query->whereBetween('created_at', [$from, $to]);
            }
        } else {
            $start_date = Carbon::now()->startOfDay();
            $end_date =Carbon::now()->endOfDay();
            $query->whereBetween('created_at', [$start_date, $end_date]);
        }

        $invoices = $query->orderBy('created_at', 'desc')->get();
        $title = "Invoices";
        $filter = session()->get('filter_params');

        if ($request->has('excel')) {
            if (count($invoices) > 0) {
                return $this->exportRecords($invoices, $title,'excel');
            } else {
                Toastr::info('no records to export');
                return redirect('payments');
            }
        }

        if ($request->has('pdf')) {
            if (count($invoices) > 0) {
                return $this->exportRecords($invoices, $title,'pdf');
            } else {
                Toastr::info('no records to export');
                return redirect('payments');
            }
        }
        return view('payments.index', get_defined_vars());
    }

    public function create($id)
    {
        $invoice = Invoice::find($id);
        if ($invoice->cleared) {
            Toastr::info("Invoice #$invoice->id cleared");
            return redirect('payments');
        }
        $payments = $invoice->payments()->orderBy('date_paid')->get();
        $payment_methods = PaymentMethod::all();
        $title = "payment for invoice #$invoice->id";
        return view('payments.create', get_defined_vars());
    }

    public function store(Request $request, $invoice_id)
    {
        $this->validate($request, [
           'date_paid' => 'required',
            'amount' => 'required',
            'payment_method' => 'required',
            'document_file' => 'required | mimes:jpeg,png,pdf'
        ]);

        $invoice = Invoice::find($invoice_id);
        $payment_method = PaymentMethod::find($request->payment_method);
        $data = [
            'invoice_id' => $invoice_id,
            'amount_paid' => $request->amount,
            'date_paid' => Carbon::parse($request->date_paid),
            'payment_method' => $payment_method->name
        ];

        $payment = $invoice->payments()->create($data);
        $latest = $invoice->tenant->statement()->orderBy('id', 'desc')->first();
        $balance = 0;
        if (count($latest) > 0) {
            $balance = -1 * ($payment->amount_paid - $latest->balance);
        }
        $statement = [
            'date' => $payment->created_at,
            'receipt_id' => $payment->id,
            'balance' => $balance,
            'debit' => $payment->amount_paid
        ];
        $invoice->tenant->statement()->create($statement);
        if ((bool) $payment) {
            $tenant = str_replace(' ', '_', strtolower($invoice->tenant->name));
            $date_paid = Carbon::parse($request->date_paid)->format('Y_m_d');
            $file = $request->file('document_file');
            $media = MediaUploader::fromSource($file)
                ->useFilename($tenant."_".$payment_method->slug."_".$date_paid."_".uniqid())
                ->toDestination('public', 'payments')
                ->upload();

            $payment->attachMedia($media, 'document');
            if ($this->clearInvoice($invoice, $invoice->payments()->sum('amount_paid'))) {
                Toastr::info("Invoice #$invoice->id cleared");
                event(new PaymentAdded($payment));
                return redirect('payments');
            }
            $message = "payment for invoice #$invoice_id made successfully";
            event(new PaymentAdded($payment));
            Toastr::success($message);
            return back();
        } else {
            $message = "error adding payment try again";
            Toastr::error($message);
            return back();
        }

    }

    public function exportRecords($records, $title, $format)
    {
        $filename = strtolower($title)."_".uniqid();
        $items = $this->transform($records);
        if ($format == 'excel') {
            return Excel::create($filename, function($excel) use ($items) {
                $excel->sheet("invoices", function($sheet) use ($items){
                    $sheet->cells('A1:Z1', function ($cells) {
                        $cells->setBackground('#9BD3FF');
                        $cells->setAlignment('center');
                        $cells->setFont([
                            'bold' => true
                        ]);
                    });
                    $sheet->setBorder('A1:Z1', 'medium');
                    $sheet->fromArray($items);
                });
            })->download('xlsx');
        } elseif($format == 'pdf') {
            $pdf = PDF::loadView('pdf.payments', get_defined_vars());
            $pdf->setPaper('A4', 'landscape');
            return $pdf->download($filename.".pdf");
        }
    }

    public function transform($records)
    {
        $items = [];

        foreach ($records as $record) {
            $item = array(
                'Tenant' => (string)$record->tenant ? $record->tenant->name : 'N/A',
                'Building' => (string)$record->property_name,
                'Floor' => (string)$record->floor_level,
                'Unit' => (string)$record->unit_number,
                'Amount Due' => (string) number_format($record->amount_payable),
                'Payment Term' => (string)$record->payment_term,
                'Rate (%)' => (string)$record->rate_of_contract != 'N/A'? : 'N/A',
                'Period' => (string)$record->period_of_contract,
                'Status' =>(string) $record->cleared ? 'paid' : 'unpaid'
            );

            array_push($items, $item);
        }

        return $items;
    }

    public function getDocument($id)
    {
        $payment = Payment::find($id);
        $path = $payment->document_url;
        return response()->download(storage_path("app/".$path));
    }
}

resources/views/payments/create.blade.php
@extends("layouts.app")
@section("title")
    {{ $title }} <a href="#" onclick="event.preventDefault()"><strong><small>See Invoice</small></strong></a>
@endsection
@section("content")
    <div class="row">
        <div class="col-md-4">
            <form action="{{ url('payments/invoices/clear/store', $invoice->id) }}" method="post"  enctype="multipart/form-data">
            <div class="card m-t-30">
                <div class="card-body">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="date_paid">Date Paid</label>
                            <input type="text" id="date_paid" name="date_paid" class="form-control" autocomplete="off">
                            @if($errors->has('date_paid'))
                                <span class="text-danger"><small>{{ $errors->first('date_paid') }}</small></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="amount">Amount Paid <small>Ksh</small></label>
                            <input type="number" id="amount" name="amount" class="form-control">
                            @if($errors->has('amount'))
                                <span class="text-danger"><small>{{ $errors->first('amount') }}</small></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="payment_method">Payment Method</label>
                            <select name="payment_method" id="payment_method" class="form-control">
                                <option value="">Select a Method</option>
                                @foreach($payment_methods as $payment_method)
                                    <option value="{{ $payment_method->id }}">{{ $payment_method->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('payment_method'))
                                <span class="text-danger"><small>{{ $errors->first('payment_method') }}</small></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="document_file">Upload Document</label>
                            <input type="file" id="document_file" name="document_file">
                            @if($errors->has('document_file'))
                                <span class="text-danger"><small>{{ $errors->first('document_file') }}</small></span>
                            @endif
                        </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">Submit</button>
                </div>
            </div>
            </form>
        </div>
        <div class="col-md-8">
            <div class="card m-t-30 m-b-30">
                <div class="card">
                    <div class="card-header">
                        Payments
                    </div>
                    <div class="card-body">
                        @if(count($payments) > 0)
                            <table class="table-striped table-condensed table">
                                <thead>
                                    <tr>
                                        <th>Date Paid</th>
                                        <th>Payment Method</th>
                                        <th>Amount</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($payments as $payment)
                                        <tr>
                                            <td>{{ $payment->date_paid }}</td>
                                            <td>{{ $payment->payment_method }}</td>
                                            <td>{{ $payment->amount_paid }}</td>
                                            <td><a href="{{ url('payments/document', $payment->id) }}" target="_blank"><i class="mdi mdi-download"></i>  Document</a> </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <div class="alert alert-info">
                                No Payments made yet
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section("modals")
    <div class="modal">
        <div class="card m-t-30 m-b-30">
            <div class="card-body invoice">
                <div class="clearfix">
                    <div class="pull-left">
                        <a href="index.html" class="logo"><i class="fa fa-home"></i> PM</a>
                    </div>
                    <div class="pull-right">
                        <h6>Invoice : #<strong>{{ $invoice->id }}</strong></h6>
                        <h6 class="pull-right">Date Generated: {{ $invoice->created_at->format('M d, Y') }}</h6>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-12">

                        <div class="pull-left mt-4">
                            <address>
                                <strong>Twitter, Inc.</strong><br>
                                795 Folsom Ave, Suite 600<br>
                                San Francisco, CA 94107<br>
                                (123) 456-7890
                            </address>
                        </div>
                        <div class="pull-right mt-4">
                            <p><strong>Payment Due on: </strong> March 15, 2015</p>
                            <p><strong>Order Status: </strong> <span class="badge badge-warning">Pending</span></p>
                            <p><strong>Order ID: </strong> #123456</p>
                        </div>
                    </div>
                </div><!--end row-->

                <div class="h-50"></div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table mt-4">
                                <thead>
                                <tr>
                                    <th>Property</th>
                                    <th>Floor Level</th>
                                    <th>Sq m Rented</th>
                                    <th>Unit Cost</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>{{ $invoice->property_name }}</td>
                                    <td>{{ $invoice->floor }}</td>
                                    <td>{{ $invoice->area_rented }}</td>
                                    <td>{{ number_format(20000) }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div><!--end row-->

                <div class="row" style="border-radius: 0px;">
                    <div class="col-md-9">
                        <p><strong>Terms And Condition : </strong></p>
                        <ul>
                            <li><small>All accounts are to be paid within 7 days from receipt of invoice. </small></li>
                            <li><small>To be paid by cheque or credit card or direct payment online.</small></li>
                            <li><small> If account is not paid within 7 days the credits details supplied as confirmation<br> of work undertaken will be charged the agreed quoted fee noted above.</small></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <p class="text-right">Payment Term: <strong>{{ $invoice->payment_term }}</strong></p>
                        <p class="text-right">Rate: <strong>{{ $invoice->rate_of_contract }}%</strong></p>
                        <p class="text-right">VAT: 12.9%</p>
                        <hr>
                        <h4 class="text-right">$ 2930.00</h4>
                    </div>
                </div><!--end row-->
                <hr>
            </div>
        </div>
    </div>
@endsection
@section("js")
    <script src="{{ get_asset('annex/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('#date_paid').datepicker({
                autoclose: true
            });
        });
    </script>
@endsection
@section("css")
    <link rel="stylesheet" href="{{ get_asset('annex/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
@endsection

resources/views/payments/index.blade.php
@extends("layouts.app")
@section("title")
    {{ $title }}
@endsection
@section("content")
    <div class="row">
        <div class="col-12">
            <div class="card m-b-5">
                <div class="card-body" style="padding: 0.5rem">
                    <form method="get" action="{{ url('payments') }}">
                        <div class="form-row align-items-center">
                            <div class="col-auto">
                                <div>
                                    <label class="mb-1"><small><strong>date generated</strong></small></label>
                                </div>
                                <div class="input-daterange input-group" id="date-range">
                                    <input type="text" class="form-control" name="from" placeholder="From Date" value="{{ set_filter_value($filter, 'from') }}">
                                    <input type="text" class="form-control" name="to" placeholder="To Date" value="{{ set_filter_value($filter, 'from') }}">
                                </div>
                            </div>
                            <div class="col-auto mt-4">
                                <button type="submit" class="btn btn-primary">Filter</button>
                                <button type="submit" name="excel" value="1" class="btn btn-success">Excel</button>
                                <button type="submit" name="pdf" value="1" class="btn btn-danger">PDF</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card m-b-30">
                <div class="card-header">
                    <h4 class="header-title pull-left mt-0">{{ $title }}</h4>
                </div>
                <div class="card-body">
                    @if(count($invoices) > 0)
                        <table class="table table-sm table-striped" id="datatable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Tenant</th>
                                <th>Property</th>
                                <th>Amount Payable</th>
                                <th>Payment Term</th>
                                <th>Due On</th>
                                <th align="right" style="width:81.2px;"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($invoices as $key => $invoice)
                                <tr>
                                    <th>{{ $key + 1 }}</th>
                                    <td>{{ (bool) $invoice->tenant ? $invoice->tenant->name : 'N?A' }}</td>
                                    <td>{{ $invoice->floor_level }} floor of {{ $invoice->property_name }} office: <strong>{{ $invoice->unit_number }}</strong></td>
                                    <td>{{ number_format($invoice->amount_payable) }}</td>
                                    <td>{{ $invoice->payment_term }}</td>
                                    <td>{{ $invoice->due_on->format('M d, Y') }}</td>
                                    <td align="right">
                                        <a href="{{ url('payments/invoices/view', $invoice->id) }}" class="btn btn-xs btn-primary" target="_blank">View</a>
                                        @if(! $invoice->cleared)
                                            <a href="{{ url('payments/invoices/clear/create', $invoice->id) }}" class="btn btn-xs btn-success" target="_blank">Clear</a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-info" role="alert">
                            <strong>No records found</strong>
                        </div>
                    @endif
                </div>
            </div>
        </div> <!-- end col -->
    </div>
@endsection
@section('js')
    <script src="{{ get_asset('annex/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        function createItem(e) {
            e.preventDefault();
        }
        $(document).ready( function () {
            $('#datatable').DataTable();
            jQuery('#date-range').datepicker({
                toggleActive: true
            });
        });
    </script>
@endsection
@section('css')

@endsection
@section('modals')
    <property-editor
            create-url="{{ url('properties/create') }}"
            update-url="{{ url('properties/update') }}"
    ></property-editor>
@endsection

resources/views/payments/payments.blade.php
@extends("layouts.app")
@section("title")
    {{ $title }}
@endsection
@section("content")
    <div class="row">
        <div class="col-12">
           <div class="row">
               <div class="col-md-12">
                   <div class="m-b-10 pull-right">
                       {{ $payments->links('vendor.pagination.bootstrap-4') }}
                   </div>
               </div>
           </div>
            <div class="row">
                <div class="col-12">
                    <div class="m-b-30">
                        <span class="pull-right"><strong>Total Amount Due:</strong> {{ number_format($invoice->amount_payable) }} Ksh</span><br>
                        <span class="pull-right"><strong>Total Paid:</strong> {{ number_format($total_paid) }} Ksh</span>
                    </div>
                </div>
            </div>
            <div class="card m-b-30">
                <div class="card-header">
                    <h4 class="header-title pull-left">{{ $title }}</h4>
                    <a href="{{ url('payments/invoices/download', $invoice->id) }}" target="_blank" class="btn btn- btn-outline-primary pull-right">download invoice</a>
                </div>
                <div class="card-body">
                    @if(count($payments) > 0)
                        <table class="table  table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Amount Paid (Ksh)</th>
                                <th>Method</th>
                                <th>Paid On</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($payments as $key => $payment)
                                <tr>
                                    <th>{{ $key + 1 }}</th>
                                    <td>{{  number_format($payment->amount_paid) }}</td>
                                    <td>{{ $payment->payment_method }}</td>
                                    <td>{{ $payment->date_paid }}</td>
                                    <td><a href="{{ url('payments/document', $payment->id) }}" target="_blank"><i class="mdi mdi-download"></i>  Document</a> </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-info" role="alert">
                            <strong>No records found</strong>
                        </div>
                    @endif
                </div>
            </div>
        </div> <!-- end col -->
    </div>
@endsection